create database PruebaTecnica;
use PruebaTecnica;

CREATE TABLE User (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FirstName VARCHAR(50) NOT NULL,
    SecondName VARCHAR(50),
    FirstLastName VARCHAR(50) NOT NULL,
    SecondLastName VARCHAR(50),
    Email VARCHAR(100) UNIQUE NOT NULL,
    PhoneNumber VARCHAR(15),
    DateOfBirth DATE NOT NULL,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE Address (
    ID INT PRIMARY KEY,
    Address TEXT NOT NULL,
    CountryName VARCHAR(50),
    CountryCode INT,
    CityName VARCHAR(50),
    CityCode INT,
    MunicipalityName VARCHAR(50),
    MunicipalityCode INT,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID) REFERENCES User(ID) ON DELETE CASCADE
);

CREATE TABLE Login (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    userName VARCHAR(20) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    status TINYINT DEFAULT 1, -- 1=Activo, 0=Inactivo
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);

CREATE TABLE Product (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL,
    Description TEXT,
    ImageURL VARCHAR(500),
    Price DECIMAL(10,2) NOT NULL,
    StockQuantity INT NOT NULL,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP, 
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE CartItem (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT DEFAULT 1,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ID) ON DELETE CASCADE
);

CREATE TABLE `Order` (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UserID INT NOT NULL,
    ShippingAddress TEXT NOT NULL,
    Status ENUM('PENDING', 'CONFIRMED', 'SHIPPED', 'DELIVERED', 'CANCELLED') DEFAULT 'PENDING',
    TotalAmount DECIMAL(10,2) NOT NULL,
    CreatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UpdatedDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES User(ID) ON DELETE CASCADE
);

CREATE TABLE OrderItem (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    OrderID INT NOT NULL,
    ProductID INT NOT NULL,
    Quantity INT NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    FOREIGN KEY (OrderID) REFERENCES `Order`(ID) ON DELETE CASCADE,
    FOREIGN KEY (ProductID) REFERENCES Product(ID) ON DELETE CASCADE
);
